baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chronologue'

[params]
copyright = "The Good Docs Project"
logo = "/img/logo.svg"

[module]
[[module.imports]]
   path = 'Chronologue'
   disable = false